### ISSUE TITLE
"reply with boss name or tier" is broken

### ISSUE THREAD

**Issue by tehstone** [KyogreBot/Kyogre#175]
different error whether tier or boss name, both need fixing

**Comment by tehstone** [comment]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "/src/meowth/__main__.py", line 5568, in _raid
    new_channel = await _raid_internal(ctx, content)
  File "/src/meowth/__main__.py", line 5678, in _raid_internal
    raid_split = new_content.strip().split()
AttributeError: 'list' object has no attribute 'strip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1017, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'list' object has no attribute 'strip'```

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "/src/meowth/__main__.py", line 5568, in _raid
    new_channel = await _raid_internal(ctx, content)
  File "/src/meowth/__main__.py", line 5654, in _raid_internal
    return await _raidegg(ctx, ' '.join([str(pokemon_msg.clean_content), new_content]))
TypeError: sequence item 1: expected str instance, list found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1017, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: sequence item 1: expected str instance, list found```
